name: Deploy Chrome Extension

on:
  push:
    branches:
      - dist  # Trigger the workflow only when changes are pushed to the `dist` branch

jobs:
  upload-extension:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Zip the extension files
    - name: Zip extension files
      run: zip -r extension.zip ./* --exclude ./.github/\* --exclude ./.git/\* 

    # Step 3: Upload to Chrome Web Store
    - name: Deploy to Chrome Web Store
      uses: cpdigitaldarkroom/publish-chrome-extension@v3.1.0
      with:
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
        zip-file: extension.zip
